apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: ankitchaure1998/hotel-image:v2

        ports:
        - containerPort: 8080

        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrete
              key: password
