kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume

spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data # Worker Node Path
